### ISSUE TITLE
Expand fields for Experiment Content Types

### ISSUE THREAD

**Issue by laceysanderson** [TripalCultivate/TripalCultivate#18]
This issue expands on Issue #4.

Specifically, this issue will focus on finalizing the fields defined for the various experiment types. The experiment types are defined in [config/install/tripal.tripalentitytype_collection.trpcultivate_experiments.yml](https://github.com/TripalCultivate/TripalCultivate/blob/4.x/config/install/tripal.tripalentitytype_collection.trpcultivate_experiments.yml) and the fields are defined in [config/install/tripal.tripalfield_collection.trpcultivate_experiments.yml](https://github.com/TripalCultivate/TripalCultivate/blob/4.x/config/install/tripal.tripalfield_collection.trpcultivate_experiments.yml). I believe all of the needed terms are already available.

Tasks:

- [x] Update all the attribution fields to use the new Chado Contact by Type field
- [x] Add additional fields specific to each experiment type

<details>

<summary>Detailed Instructions: switch to Chado Contact by Role field</summary>

Edit the [config/install/tripal.tripalfield_collection.trpcultivate_experiments.yml](https://github.com/TripalCultivate/TripalCultivate/blob/4.x/config/install/tripal.tripalfield_collection.trpcultivate_experiments.yml) file is VS Code.

For each field block with a todo mentioning the chado_contact_type_default field such as the following example:
```
    # @todo update to chado_contact_type_default with type specified Tripal#1845
    -   name: experiment_datacollector
        content_type: field_experiment
        label: Data Collector
        type: chado_property_type_default
        description: The researcher(s) and/or staff who are collecting the data. This includes anyone recording measurements/data (e.g. field staff taking flowering time notes, lab technican measuring gene expression)
        cardinality: -1
        required: false
        storage_settings:
            storage_plugin_id: chado_storage
            storage_plugin_settings:
                base_table: project
                prop_table: projectprop
        settings:
            termIdSpace: AGRO
            termAccession: 00000379
        display:
          view:
            default:
              region: content
              label: above
              weight: 20
          form:
            default:
              region: content
              weight: 20
```
You will want to make two specific changes:
1. Change the field type from Chado Property (chado_property_type_default) to Chado Contact by Role (chado_contact_by_role_type_default).
```diff
    # @todo update to chado_contact_type_default with type specified Tripal#1845
    -   name: experiment_datacollector
        content_type: field_experiment
        label: Data Collector
-         type: chado_property_type_default
+         type: chado_contact_by_role_type_default
        description: The researcher(s) and/or staff who are collecting the data. This includes anyone recording measurements/data (e.g. field staff taking flowering time notes, lab technican measuring gene expression)
        cardinality: -1
        required: false
        storage_settings:
            storage_plugin_id: chado_storage
            storage_plugin_settings:
                base_table: project
                prop_table: projectprop
        settings:
            termIdSpace: AGRO
            termAccession: 00000379
        display:
          view:
            default:
              region: content
              label: above
              weight: 20
          form:
            default:
              region: content
              weight: 20
```
2. Change storage information to use the contact table instead of the projectprop table.
```diff
    # @todo update to chado_contact_type_default with type specified Tripal#1845
    -   name: experiment_datacollector
        content_type: field_experiment
        label: Data Collector
        type: chado_property_type_default
        description: The researcher(s) and/or staff who are collecting the data. This includes anyone recording measurements/data (e.g. field staff taking flowering time notes, lab technican measuring gene expression)
        cardinality: -1
        required: false
        storage_settings:
            storage_plugin_id: chado_storage
            storage_plugin_settings:
-                 base_table: project
-                 prop_table: projectprop
+                 base_table: project
+                 linker_table: project_contact
+                 linker_fkey_column: contact_id
        settings:
            termIdSpace: AGRO
            termAccession: 00000379
        display:
          view:
            default:
              region: content
              label: above
              weight: 20
          form:
            default:
              region: content
              weight: 20
```

</details>

<details open>

<summary>Detailed Instructions: Specific Metadata fields per Experiment type</summary>

Edit the [config/install/tripal.tripalfield_collection.trpcultivate_experiments.yml](https://github.com/TripalCultivate/TripalCultivate/blob/4.x/config/install/tripal.tripalfield_collection.trpcultivate_experiments.yml) file in VS Code.

For this task we will want to add field blocks for each experiment type. Specifically, we want to add a number of Chado Property fields for various metadata specific to each experiment type (e.g. siteyear for Field Experiments).

### Field Block Template

The following YAML block defines a single chado property field. I've added placeholders in ALL CAPS to indicate the parts that need to change for each field.

```yaml
    -   name: FIELD-INSTANCE-MACHINE-NAME
        content_type: EXPERIMENT-TYPE-MACHINE-NAME
        label: FIELD-INSTANCE-HUMAN_READABLE-NAME
        type: chado_property_type_default
        description: HELP_TEXT
        cardinality: -1
        required: false
        storage_settings:
            storage_plugin_id: chado_storage
            storage_plugin_settings:
                base_table: project
                prop_table: projectprop
        settings:
            termIdSpace: TERM-DB-NAME
            termAccession: TERM-DBXREF-ACCESSION
        display:
          view:
            default:
              region: content
              label: above
              weight: 20
          form:
            default:
              region: content
              weight: 20
```

</details>

The `EXPERIMENT-TYPE-MACHINE-NAME` should be one of field_experiment, greenhouse_experiment, growthchamber_experiment, biochem_experiment, ecosystem_survey.

The remaining placeholders are specific to each field being added.

Steps:

- [x] Determine which metadata fields we want to add for each experiment type. Use KnowPulse as a starting place by looking up the ones we defined for the Phenotype Experiment which loosely maps to the field experiment.
- [x] Make a list/spreadsheet where each row is a field to be added and the columns are Human-readable Name, Machine Name, Term DB.name, Term Dbxref.accession, help text and fill this out for all the metadata identified in the first step.
- [x] Add a field block to the YAML for each row in the spreadsheet. The field blocks are added to the end of each section of fields for a given experiment type. More specifically, find the last field block mentioning a specific experiment type, then place your new blocks after it. Keep field blocks separated by an empty line.

## Development

Development is being carried out on branch `g1.04-studyExperimentFields` and the following instructions walk you through how to setup the development environment.

1. Clone this repository into a local directory on your computer.
```
cd ~/Dockers
git clone https://github.com/TripalCultivate/TripalCultivate trpcult-18-experimentFields
cd trpcult-18-experimentFields
git checkout g1.04-studyExperimentFields
```
3. Build the docker image on this branch.
```
docker build --build-arg drupalversion=10.2.x-dev --build-arg phpversion=8.3 --tag=trpcultivate-base:18-experimentFields ./
```
4. Run a container so that you can test through the interface.
```
docker run --publish=80:80 -tid --name=base18 --volume=$(pwd):/var/www/drupal/web/modules/contrib/TripalCultivate trpcultivate-base:18-experimentFields
docker exec base18 service postgresql restart
```
5. Login using the [Tripaldocker credentials](https://tripaldoc.readthedocs.io/en/latest/install/docker.html#development-site-information).

You can confirm the content types we expect are created by going to http://localhost/admin/structure/bio_data. You expect to see these Experiment content types:
![Screenshot 2024-05-15 at 3 32 14 PM](https://github.com/TripalCultivate/TripalCultivate/assets/1566301/0671c55b-7ae3-4068-af1c-cc7e16062be7)
Then you want to look at the fields. You can get there by clicking the arrow and then "Manage fields" in the drop down as shown for "Field Experiment" in the above screenshot. This is where you will check the work you have done.

## Testing changes to content type fields

Each time you make a change to the fields yaml file you will need to completely rebuild the image and restart the container. The following commands delete the existing image and container first and then rebuild and rerun.
```
docker container rm base18
docker image rm trpcultivate-base:18-experimentFields
docker build --build-arg drupalversion=10.2.x-dev --build-arg phpversion=8.3 --tag=trpcultivate-base:18-experimentFields ./
docker run --publish=80:80 -tid --name=base18 --volume=$(pwd):/var/www/drupal/web/modules/contrib/TripalCultivate trpcultivate-base:18-experimentFields
docker exec base18 service postgresql restart
```
